ALTER TABLE tenants
    ADD COLUMN IF NOT EXISTS hmac_key_id TEXT NOT NULL DEFAULT 'v1',
    ADD COLUMN IF NOT EXISTS hmac_prev_secret TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS hmac_prev_key_id TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS hmac_prev_until TIMESTAMPTZ;
